version: '2.4'

services:
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.0
    container_name: es01
    networks:
      - elastic
    ports:
      - "9200:9200"
    environment:
      - "discovery.type=single-node"
    volumes:
      - /mnt/p/d/Thomas/Search/elasticsearch2:/usr/share/elasticsearch/data
    mem_limit: 1g
    restart: unless-stopped

networks:
  elastic:
    driver: bridge

